WindowsDataTypes( wdt ) {

    ; flag = 0 -- > Size
    ; flag = 1 -- > AhkDataType
    GoTo( "_Types" )

    Ini:
    
        if( types.Has( wdt ) ) {
            return types[ wdt ]
        }
        return 0

    _Types:

        static types :=
                Map( 
                    "ATOM", ["USHORT", 2],
                    "BOOL", ["INT", 4],
                    "BOOLEAN", ["UCHAR", 1],
                    "BYTE", ["UCHAR", 1],
                    "COLORREF", ["UINT", 4],
                    "DWORD", ["UINT", 4],
                    "DWORD_PTR", ["UPTR", A_PtrSize],
                    "DWORD32", ["UINT", 4],
                    "DWORD64", ["UINT64", 8],
                    "DWORDLONG", ["UINT64", 8],
                    "HACCEL", ["UPTR", A_PtrSize],
                    "HALF_PTR", ["A_PtrSize", A_PtrSize],
                    "HANDLE", ["UPTR", A_PtrSize],
                    "HBITMAP", ["UPTR", A_PtrSize],
                    "HBRUSH", ["UPTR", A_PtrSize],
                    "HCOLORSPACE", ["UPTR", A_PtrSize],
                    "HCONV", ["UPTR", A_PtrSize],
                    "HCONVLIST", ["UPTR", A_PtrSize],
                    "HCURSOR", ["UPTR", A_PtrSize],
                    "HDC", ["UPTR", A_PtrSize],
                    "HDDEDATA", ["UPTR", A_PtrSize],
                    "HDESK", ["UPTR", A_PtrSize],
                    "HDROP", ["UPTR", A_PtrSize],
                    "HDWP", ["UPTR", A_PtrSize],
                    "HENHMETAFILE", ["UPTR", A_PtrSize],
                    "HFILE", ["PTR", A_PtrSize],
                    "HFONT", ["UPTR", A_PtrSize],
                    "HGDIOBJ", ["UPTR", A_PtrSize],
                    "HGLOBAL", ["UPTR", A_PtrSize],
                    "HHOOK", ["UPTR", A_PtrSize],
                    "HICON", ["UPTR", A_PtrSize],
                    "HINSTANCE", ["UPTR", A_PtrSize],
                    "HKEY", ["UPTR", A_PtrSize],
                    "HKL", ["UPTR", A_PtrSize],
                    "HLOCAL", ["UPTR", A_PtrSize],
                    "HMENU", ["UPTR", A_PtrSize],
                    "HMETAFILE", ["UPTR", A_PtrSize],
                    "HMODULE", ["UPTR", A_PtrSize],
                    "HMONITOR", ["UPTR", A_PtrSize],
                    "HPALETTE", ["UPTR", A_PtrSize],
                    "HPEN", ["UPTR", A_PtrSize],
                    "HRESULT", ["PTR", A_PtrSize],
                    "HRGN", ["UPTR", A_PtrSize],
                    "HRSRC", ["UPTR", A_PtrSize],
                    "HSZ", ["UPTR", A_PtrSize],
                    "HWINSTA", ["UPTR", A_PtrSize],
                    "HWND", ["UPTR", A_PtrSize],
                    "INT_PTR", ["PTR", A_PtrSize],
                    "INT32", ["INT", 4],
                    "LANGID", ["USHORT", 2],
                    "LCID", ["UINT", 4],
                    "LCTYPE", ["UINT", 4],
                    "LGRPID", ["UINT", 4],
                    "LONG", ["INT", 4],
                    "LONG_PTR", ["PTR", A_PtrSize],
                    "LONG32", ["INT", 4],
                    "LONG64", ["INT64", 8],
                    "LONGLONG", ["INT64", 8],
                    "LPARAM", ["UPTR", A_PtrSize],
                    "LPBOOL", ["UPTR", A_PtrSize],
                    "LPBYTE", ["UPTR", A_PtrSize],
                    "LPCOLORREF", ["UPTR", A_PtrSize],
                    "LPCSTR", ["UPTR", A_PtrSize],
                    "LPCTSTR", ["UPTR", A_PtrSize],
                    "LPCVOID", ["UPTR", A_PtrSize],
                    "LPCWSTR", ["UPTR", A_PtrSize],
                    "LPDWORD", ["UPTR", A_PtrSize],
                    "LPHANDLE", ["UPTR", A_PtrSize],
                    "LPINT", ["UPTR", A_PtrSize],
                    "LPLONG", ["UPTR", A_PtrSize],
                    "LPSTR", ["UPTR", A_PtrSize],
                    "LPTSTR", ["UPTR", A_PtrSize],
                    "LPVOID", ["UPTR", A_PtrSize],
                    "LPWORD", ["UPTR", A_PtrSize],
                    "LPWSTR", ["UPTR", A_PtrSize],
                    "LRESULT", ["UINT", 4],
                    "PBOOL", ["UINT", 4],
                    "PBOOLEAN", ["UINT", 4],
                    "PBYTE", ["UINT", 4],
                    "PCHAR", ["UINT", 4],
                    "PCSTR", ["UINT", 4],
                    "PCTSTR", ["UINT", 4],
                    "PCWSTR", ["UINT", 4],
                    "PDWORD", ["UINT", 4],
                    "PDWORD_PTR", ["UINT", 4],
                    "PDWORD32", ["UINT", 4],
                    "PDWORD64", ["UINT", 4],
                    "PDWORDLONG", ["UINT", 4],
                    "PFLOAT", ["UINT", 4],
                    "PHALF_PTR", ["UINT", 4],
                    "PHANDLE", ["UPTR", A_PtrSize],
                    "PHKEY", ["UPTR", A_PtrSize],
                    "PINT", ["UPTR", A_PtrSize],
                    "PINT_PTR", ["UPTR", A_PtrSize],
                    "PINT32", ["UPTR", A_PtrSize],
                    "PINT64", ["UPTR", A_PtrSize],
                    "PLCID", ["UPTR", A_PtrSize],
                    "PLONG", ["UPTR", A_PtrSize],
                    "PLONG_PTR", ["UPTR", A_PtrSize],
                    "PLONG32", ["UPTR", A_PtrSize],
                    "PLONG64", ["UPTR", A_PtrSize],
                    "PLONGLONG", ["UPTR", A_PtrSize],
                    "POINTER_32", ["UPTR", A_PtrSize],
                    "POINTER_64", ["PTR", A_PtrSize],
                    "POINTER_SIGNED", ["PTR", A_PtrSize],
                    "POINTER_UNSIGNED", ["UPTR", A_PtrSize],
                    "PSHORT", ["UPTR", A_PtrSize],
                    "PSIZE_T", ["UPTR", A_PtrSize],
                    "PSSIZE_T", ["UPTR", A_PtrSize],
                    "PSTR", ["UPTR", A_PtrSize],
                    "PTBYTE", ["UPTR", A_PtrSize],
                    "PTCHAR", ["UPTR", A_PtrSize],
                    "PTSTR", ["UPTR", A_PtrSize],
                    "PUCHAR", ["UPTR", A_PtrSize],
                    "PUHALF_PTR", ["UPTR", A_PtrSize],
                    "PUINT", ["UPTR", A_PtrSize],
                    "PUINT_PTR", ["UPTR", A_PtrSize],
                    "PUINT32", ["UPTR", A_PtrSize],
                    "PUINT64", ["UPTR", A_PtrSize],
                    "PULONG", ["UPTR", A_PtrSize],
                    "PULONG_PTR", ["UPTR", A_PtrSize],
                    "PULONG32", ["UPTR", A_PtrSize],
                    "PULONG64", ["UPTR", A_PtrSize],
                    "PULONGLONG", ["UPTR", A_PtrSize],
                    "PUSHORT", ["UPTR", A_PtrSize],
                    "PVOID", ["UPTR", A_PtrSize],
                    "PWCHAR", ["UPTR", A_PtrSize],
                    "PWORD", ["UPTR", A_PtrSize],
                    "PWSTR", ["UPTR", A_PtrSize],
                    "SC_HANDLE", ["UPTR", A_PtrSize],
                    "SC_LOCK", ["UPTR", A_PtrSize],
                    "SERVICE_STATUS_HANDLE", ["UPTR", A_PtrSize],
                    "SIZE_T", ["UPTR", A_PtrSize],
                    "SSIZE_T", ["PTR", A_PtrSize],
                    "TBYTE", ["CHAR", 1],
                    "TCHAR", ["USHORT", 2],
                    "UHALF_PTR", ["A_PtrSize", A_PtrSize],
                    "UINT_PTR", ["UPTR", A_PtrSize],
                    "UINT32", ["UINT", 4],
                    "UINT64", ["UINT64", 8],
                    "ULONG", ["UINT", 4],
                    "ULONG_PTR", ["UPTR", A_PtrSize],
                    "ULONG32", ["UINT", 4],
                    "ULONG64", ["UINT64", 8],
                    "ULONGLONG", ["UINT64", 8],
                    "USN", ["INT64", 8],
                    "WCHAR", ["USHORT", 2],
                    "WORD", ["USHORT", 2],
                    "WPARAM", ["PTR", A_PtrSize]
                )

    GoTo( "Ini" )

}